# Generated by Django 4.2.1 on 2023-05-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'День для проверки посещаемости',
                'verbose_name_plural': 'Дни для проверки посещаемости',
            },
        ),
        migrations.CreateModel(
            name='DayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время')),
                ('has_reason', models.BooleanField(verbose_name='Есть причина')),
                ('about_reason', models.TextField(blank=True, null=True, verbose_name='Описание причины')),
                ('coins', models.IntegerField(default=0, verbose_name='Сноукоины')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='FineDayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='attendance.day')),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_day_users', to='attendance.fine')),
            ],
        ),
    ]
