# Generated by Django 4.2.1 on 2023-05-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finedayuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayuser',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.day'),
        ),
        migrations.AddField(
            model_name='dayuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
